spring.application.name=22806187931_nguyentrungthanh
spring.datasource.url=jdbc:mysql://localhost:3306/demoproduct
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update